"""init

Revision ID: 522d83c0dfbf
Revises:
Create Date: 2025-02-08 16:09:47.828514

"""

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "522d83c0dfbf"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activity",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("parent_activity_id", sa.BigInteger(), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(["parent_activity_id"], ["activity.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "building",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("adress", sa.String(), nullable=False),
        sa.Column(
            "geo_coords",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "organization",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("mobile_phone", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("building_id", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(["building_id"], ["building.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "activity_organization",
        sa.Column("activity_id", sa.BigInteger(), nullable=False),
        sa.Column("organization_id", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(["activity_id"], ["activity.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organization.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("activity_id", "organization_id", "id"),
    )
    op.execute("""
        INSERT INTO
            building(adress, geo_coords )
        VALUES
            ('г. Москва, ул. Ленина 1, офис 3', ST_SetSRID(ST_MakePoint(37.6173, 55.7558), 4326)),
            ('г. Москва, ул. Пушкина 1, офис 3', ST_SetSRID(ST_MakePoint(38.6173, 56.7558), 4326));
    """)  # noqa: RUF001
    op.execute("""
        INSERT INTO
            organization(name, mobile_phone, building_id)
        VALUES
            ('ООО Ромашка', '{"77777777777", "77777777778"}', 1),
            ('ООО Лютик', '{"77777777779"}', 1);
    """)  # noqa: RUF001
    op.execute("""
        INSERT INTO
            activity(name, parent_activity_id)
        VALUES
            ('Еда', null),
            ('Мясная продукция', 1),
            ('Молочная продукция', 1),
            ('Автомобили', null),
            ('Грузовые', 4),
            ('Легковые', 4);
    """)
    op.execute("""
        INSERT INTO
            activity_organization(organization_id, activity_id)
        VALUES
            (1, 2),
            (1, 3),
            (2, 4);
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("activity_organization")
    op.drop_table("organization")
    op.drop_table("building")
    op.drop_table("activity")
    # ### end Alembic commands ###
